/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as ApiEventsProjectIdRouteImport } from './routes/api/events/$projectId'

const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectRoute,
} as any)
const ApiEventsProjectIdRoute = ApiEventsProjectIdRouteImport.update({
  id: '/api/events/$projectId',
  path: '/api/events/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/project': typeof ProjectRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/events/$projectId': typeof ApiEventsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/project': typeof ProjectRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/events/$projectId': typeof ApiEventsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/project': typeof ProjectRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/events/$projectId': typeof ApiEventsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/project'
    | '/project/$projectId'
    | '/api/events/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/project'
    | '/project/$projectId'
    | '/api/events/$projectId'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/project'
    | '/project/$projectId'
    | '/api/events/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  ProjectRoute: typeof ProjectRouteWithChildren
  ApiEventsProjectIdRoute: typeof ApiEventsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/api/events/$projectId': {
      id: '/api/events/$projectId'
      path: '/api/events/$projectId'
      fullPath: '/api/events/$projectId'
      preLoaderRoute: typeof ApiEventsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectRouteChildren {
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
}

const ProjectRouteChildren: ProjectRouteChildren = {
  ProjectProjectIdRoute: ProjectProjectIdRoute,
}

const ProjectRouteWithChildren =
  ProjectRoute._addFileChildren(ProjectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  ProjectRoute: ProjectRouteWithChildren,
  ApiEventsProjectIdRoute: ApiEventsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
