/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as ApiLogsRouteImport } from './routes/api/logs'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project/$projectId/index'
import { Route as ProjectProjectIdReviewRouteImport } from './routes/project/$projectId/review'
import { Route as ProjectProjectIdPreviewRouteImport } from './routes/project/$projectId/preview'
import { Route as ApiEventsProjectIdRouteImport } from './routes/api/events/$projectId'
import { Route as ProjectProjectIdReviewIndexRouteImport } from './routes/project/$projectId/review/index'
import { Route as ProjectProjectIdReviewTaskIdRouteImport } from './routes/project/$projectId/review/$taskId'

const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectRoute,
} as any)
const ApiLogsRoute = ApiLogsRouteImport.update({
  id: '/api/logs',
  path: '/api/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdReviewRoute = ProjectProjectIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdPreviewRoute = ProjectProjectIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ApiEventsProjectIdRoute = ApiEventsProjectIdRouteImport.update({
  id: '/api/events/$projectId',
  path: '/api/events/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdReviewIndexRoute =
  ProjectProjectIdReviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectProjectIdReviewRoute,
  } as any)
const ProjectProjectIdReviewTaskIdRoute =
  ProjectProjectIdReviewTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => ProjectProjectIdReviewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/project': typeof ProjectRouteWithChildren
  '/api/logs': typeof ApiLogsRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/api/events/$projectId': typeof ApiEventsProjectIdRoute
  '/project/$projectId/preview': typeof ProjectProjectIdPreviewRoute
  '/project/$projectId/review': typeof ProjectProjectIdReviewRouteWithChildren
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/review/$taskId': typeof ProjectProjectIdReviewTaskIdRoute
  '/project/$projectId/review/': typeof ProjectProjectIdReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/project': typeof ProjectRouteWithChildren
  '/api/logs': typeof ApiLogsRoute
  '/api/events/$projectId': typeof ApiEventsProjectIdRoute
  '/project/$projectId/preview': typeof ProjectProjectIdPreviewRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/review/$taskId': typeof ProjectProjectIdReviewTaskIdRoute
  '/project/$projectId/review': typeof ProjectProjectIdReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/project': typeof ProjectRouteWithChildren
  '/api/logs': typeof ApiLogsRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/api/events/$projectId': typeof ApiEventsProjectIdRoute
  '/project/$projectId/preview': typeof ProjectProjectIdPreviewRoute
  '/project/$projectId/review': typeof ProjectProjectIdReviewRouteWithChildren
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/review/$taskId': typeof ProjectProjectIdReviewTaskIdRoute
  '/project/$projectId/review/': typeof ProjectProjectIdReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/project'
    | '/api/logs'
    | '/project/$projectId'
    | '/api/events/$projectId'
    | '/project/$projectId/preview'
    | '/project/$projectId/review'
    | '/project/$projectId/'
    | '/project/$projectId/review/$taskId'
    | '/project/$projectId/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/project'
    | '/api/logs'
    | '/api/events/$projectId'
    | '/project/$projectId/preview'
    | '/project/$projectId'
    | '/project/$projectId/review/$taskId'
    | '/project/$projectId/review'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/project'
    | '/api/logs'
    | '/project/$projectId'
    | '/api/events/$projectId'
    | '/project/$projectId/preview'
    | '/project/$projectId/review'
    | '/project/$projectId/'
    | '/project/$projectId/review/$taskId'
    | '/project/$projectId/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  ProjectRoute: typeof ProjectRouteWithChildren
  ApiLogsRoute: typeof ApiLogsRoute
  ApiEventsProjectIdRoute: typeof ApiEventsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/api/logs': {
      id: '/api/logs'
      path: '/api/logs'
      fullPath: '/api/logs'
      preLoaderRoute: typeof ApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/review': {
      id: '/project/$projectId/review'
      path: '/review'
      fullPath: '/project/$projectId/review'
      preLoaderRoute: typeof ProjectProjectIdReviewRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/preview': {
      id: '/project/$projectId/preview'
      path: '/preview'
      fullPath: '/project/$projectId/preview'
      preLoaderRoute: typeof ProjectProjectIdPreviewRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/api/events/$projectId': {
      id: '/api/events/$projectId'
      path: '/api/events/$projectId'
      fullPath: '/api/events/$projectId'
      preLoaderRoute: typeof ApiEventsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/review/': {
      id: '/project/$projectId/review/'
      path: '/'
      fullPath: '/project/$projectId/review/'
      preLoaderRoute: typeof ProjectProjectIdReviewIndexRouteImport
      parentRoute: typeof ProjectProjectIdReviewRoute
    }
    '/project/$projectId/review/$taskId': {
      id: '/project/$projectId/review/$taskId'
      path: '/$taskId'
      fullPath: '/project/$projectId/review/$taskId'
      preLoaderRoute: typeof ProjectProjectIdReviewTaskIdRouteImport
      parentRoute: typeof ProjectProjectIdReviewRoute
    }
  }
}

interface ProjectProjectIdReviewRouteChildren {
  ProjectProjectIdReviewTaskIdRoute: typeof ProjectProjectIdReviewTaskIdRoute
  ProjectProjectIdReviewIndexRoute: typeof ProjectProjectIdReviewIndexRoute
}

const ProjectProjectIdReviewRouteChildren: ProjectProjectIdReviewRouteChildren =
  {
    ProjectProjectIdReviewTaskIdRoute: ProjectProjectIdReviewTaskIdRoute,
    ProjectProjectIdReviewIndexRoute: ProjectProjectIdReviewIndexRoute,
  }

const ProjectProjectIdReviewRouteWithChildren =
  ProjectProjectIdReviewRoute._addFileChildren(
    ProjectProjectIdReviewRouteChildren,
  )

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdPreviewRoute: typeof ProjectProjectIdPreviewRoute
  ProjectProjectIdReviewRoute: typeof ProjectProjectIdReviewRouteWithChildren
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdPreviewRoute: ProjectProjectIdPreviewRoute,
  ProjectProjectIdReviewRoute: ProjectProjectIdReviewRouteWithChildren,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

interface ProjectRouteChildren {
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

const ProjectRouteChildren: ProjectRouteChildren = {
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}

const ProjectRouteWithChildren =
  ProjectRoute._addFileChildren(ProjectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  ProjectRoute: ProjectRouteWithChildren,
  ApiLogsRoute: ApiLogsRoute,
  ApiEventsProjectIdRoute: ApiEventsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
